dependencies:
- name: postgresql
  version: 0.8.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: blackfire
  version: 0.1.0
  repository: https://tech.sparkfabrik.com/blackfire-chart/
  condition: blackfire.enabled
- name: external-dns
  version: 1.3.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: externaldns.enabled
