# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

php:
  repository: "eu.gcr.io/${PROJECT_ID}/php"
  tag: latest
  pullPolicy: Always
  replicaCount: 1
  mercure:
    jwtSecret: ""
  jwt:
    secretKey: ""
    publicKey: ""
    passphrase: ""
  env: prod
  debug: '0'
  secret: ""
  corsAllowOrigin: "^https?://(.*?api-platform\\.com|localhost(?::[0-9]+)?)$"
  trustedHosts: "^.*\\.api\\-platform\\.com$"
  trustedProxies:
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 104.16.0.0/12
    - 108.162.192.0/18
    - 131.0.72.0/22
    - 141.101.64.0/18
    - 162.158.0.0/15
    - 172.64.0.0/13
    - 173.245.48.0/20
    - 188.114.96.0/20
    - 190.93.240.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

nginx:
  repository: "eu.gcr.io/${PROJECT_ID}/nginx"
  tag: latest
  pullPolicy: Always
  replicaCount: 1

varnish:
  enabled: true
  #url: https://example.com
  repository: "eu.gcr.io/${PROJECT_ID}/varnish"
  tag: latest
  pullPolicy: Always
  replicaCount: 1

postgresql:
  enabled: true
  # If bringing your own PostgreSQL, the full uri to use
  #url: pgsql://api-platform:!ChangeMe!@example.com/api?serverVersion=10
  postgresqlUsername: "api-platform"
  postgresqlPassword: ""
  postgresqlDatabase: "api"
  # Persistent Volume Storage configuration.
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  persistence:
    enabled: false
  pullPolicy: IfNotPresent
  image:
    repository: bitnami/postgresql
    tag: 10

mercure:
  enabled: true
  publishUrl: http://mercure/hub
  subscribeUrl: https://demo-mercure.api-platform.com/hub
  allowAnonymous: "1"
  corsAllowedOrigins: "^https?://.*?\\.api-platform\\.com$"
  acmeHosts: "" # TODO: Fix the Mercure chart
  service:
    type: NodePort
    port: 80

external-dns:
  enabled: true
  domainFilters:
    - api-platform.com
  provider: cloudflare
  cloudflare:
    apiKey: ""
    email: ""
  rbac:
    create: true

ingress:
  annotations:
    # kubernetes.io/ingress.global-static-ip-name: chart-ip
    # kubernetes.io/ingress.class: gce
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace, you can also use cert-manager.
    # - hosts:
      # - demo.api-platform.com
      # - demo-mercure.api-platform.com
  hosts:
    api:
      host: demo.api-platform.com
      serviceName: varnish
    mercure:
      host: demo-mercure.api-platform.com
      serviceName: mercure

blackfire:
  blackfire:
    enabled: false
  image:
    tag: latest

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
