apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}-php
  labels:
    app: {{ template "name" . }}-php
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.php.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-php
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-php
          image: "{{ .Values.php.repository }}:{{ .Values.php.tag }}"
          imagePullPolicy: {{ .Values.php.pullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: trusted-proxies
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: env
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: debug
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: cors-allow-origin
            - name: VARNISH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: varnish-url
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-url
            - name: MERCURE_PUBLISH_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-publish-url
            - name: MERCURE_SUBSCRIBE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-subscribe-url
            - name: MERCURE_JWT
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-jwt
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
