sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - admin/node_modules
    - client/node_modules

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.6.1-linux-amd64.tar.gz
  - tar xzf helm-v2.6.1-linux-amd64.tar.gz
  - npm install -g react-scripts
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - docker-compose up -d
  - linux-amd64/helm lint api/helm/api/
  - sleep 20
  - sh -c "cd admin && PUBLIC_URL="/api-demo-admin-test" yarn install && yarn build"
  - sh -c "cd client && PUBLIC_URL="/api-demo-client-test" yarn install && yarn build"
  - docker-compose exec php composer install -o -n
  - docker-compose exec php bin/console security:check
  - docker-compose exec php bin/console doctrine:schema:validate --skip-sync
  - docker-compose exec php bin/console doctrine:schema:drop --force
  - docker-compose exec php bin/console doctrine:schema:create
  - docker-compose exec php bin/console hautelook:fixtures:load -n
  - docker-compose exec php bin/console doctrine:schema:drop --env=test --force
  - docker-compose exec php bin/console cache:warmup --env=test
  - docker-compose exec php bin/behat
  - curl http://localhost
  - curl http://localhost:81
  - curl http://localhost:8080
  - curl http://localhost:8081
  - curl -k https://localhost
  - curl -k https://localhost:444
  - curl -k https://localhost:8443
  - curl -k https://localhost:8444