language: php

dist: trusty

sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - admin/node_modules
    - client/node_modules

# If you want to use multi branch deployment or branch naming, set MULTI_BRANCH value to 1 and set your DEPLOYMENT_BRANCH.
# Don't forget to change the repo name to fit your needs.
# If you need explanation about Parameter expansion, just see https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
# TODO change the name of the service account to CI_SERVICE_ACCOUNT here, in GCP and in CI repositories env var in order to improve reusability and be able to use before_install.sh script in before_install stage.
env:
  global:
    - BRANCH=${TRAVIS_BRANCH}
    - BRANCH=`echo $BRANCH | sed -E "s/\//-/g"`
    - BRANCH=${BRANCH,,}

# Check that all needed travis environment variables are set.
# When working in dev branchs we don't want to override the master builds so we need to define Ã  DEV_ADMIN_BUCKET and a DEV_CLIENT_BUCKET.
# If you really want branch naming, you can instead create buckets on the fly using subdomains e.g  gs://${BRANCH}.you-domain.com
before_install:
  - nvm install node
  - ./ci/before_install.sh
  - source ./ci/.env

before_script:
  - phpenv config-rm xdebug.ini
  - sudo service mysql stop
  - sudo service postgresql stop
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash -s -- --version v2.11.0;
  - npm install -g react-scripts
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
#  - ./ci/test.sh
  - echo test

# Get kubectl and make it executable
# Create the travis service account access file from travis environment variables
# Connect to the project as travis service account by gcloud using the travis service account access file we just created above and configure project.
# Create the needed bucket in which to push builds.
before_deploy:
  - ./ci/before_deploy.sh
  - |
    if [[ "${MULTI_BRANCH}" == "0" && "${CURRENT_CI}" == "travis" ]]; then
      gsutil mb -p ${PROJECT_ID} -l eu gs://${ADMIN_BUCKET} || echo "Admin bucket exists";
      gsutil mb -p ${PROJECT_ID} -l eu gs://${CLIENT_BUCKET} || echo "Client bucket exists";
    elif [[ "${CURRENT_CI}" == "travis" ]]
    then
      gsutil mb -p ${PROJECT_ID} -l eu gs://${DEV_ADMIN_BUCKET} || echo "Dev admin bucket exists"
      gsutil mb -p ${PROJECT_ID} -l eu gs://${DEV_CLIENT_BUCKET} || echo "Dev client bucket exists"
    fi;

# Deploy images and buckets according to the current context, create or update Kubenetes release with updated informations.
deploy:
  - provider: script
    script: bash ci/deploy.sh
    skip_cleanup: true
    on:
      branch: ${DEPLOYMENT_BRANCH}
      repo: ${REPOSITORY}
      condition: "$MULTI_BRANCH == 0 && $CURRENT_CI == 'travis'"
  - provider: script
    script: bash ci/deploy.sh
    skip_cleanup: true
    on:
      repo: ${REPOSITORY}
      condition: "$MULTI_BRANCH == 1 && $CURRENT_CI == 'travis'"
#  - provider: gcs
#    access_key_id:
#      secure: eSJfigRfZp7bwMBT61tes4NZZR5UnPSACWuD3seeLyMMflvfEiQBT30kMyQkcIA19cYUWuzCmdaUDGuphj8KrkPOfIqoPaG5ZM/zFbjgtJs3nNmpMt2GW/y5YFSqJR7ha0TYCUpPq9UonxEB/sdcifS7JRS0PmeEotZbcKMGmiCzDnFR8fNbDC1w1XZEfFoV+xtBYJCCDsZpPVjt+GXI+3OX31qnRCMv89aPU2lgmbUaF3oM+Bxc+9jQPEUmMKzOXt1AlIscJgkjyOIPTU9R1TsYtSNGzCxhEj2EtBdbtr2SKLdvJCaxABDtg6c0DOZSRSB5FP2kjLXm2TmtnFyn04R2RS7Cp3F5tueSpiK/51rI6oPc66OYMtWSINMhQzzWTiAdkBx2sekO9InbBgJMJgbcWt5nRvtzS/4mbCiDJxM+H4LuJHaqeCdDqZ51M1mf1HBh0diKIEn0o86fzUlPBtLZBLo/PCqGsJnLF+7VkG0AHExuJCSx8QHXfvP40+D3LtameHopx0lK+L8CMWwRzGJ5SDzzpfqoWZxwyzZjEvLzOdChWRb9jqPQDC1H48SFhsQt/eiwz0ZQq4v8I8DqQ3NkECYBoVgO7ozGN/pnqYK3i8xRnA47dGvSZrxQB32Eq0mkF6s8Rk7Xt6dI5ppNqdzjrCK2ZWijcGjBIQ769gQ=
#    secret_access_key:
#      secure: O4nNU4GlxBpnp1lJEEZKm0R3iUhK2V6qpu2JTxI4Vip6E5oAvXWJBc8keT75vbodRG2yYgmCf4HZhDnZRso6B7zY1SbE+oJjS6/jWM/Qkynf4qJ2/5NRvxjTuQsp99eqmclQ9J5CwhU690ZSZgC8eFaGN5Dwa2yJu5kBZHeUiDQgO3o3n1a2YCHBnOwQy7O7h6wj6d3iLThpfpdpLheqLF0DQ/c593Yy5mQgZRZkuqhLGWe94h8WyUtzJCmmYVP+XKNxbNKysCpD6zUulVTQ4XBYf5Z8kI2pAEP8UsTjqLZBjKdpyYqxoigyoL78hgs7KrYUBcCKW9qUsjRdXgNrsVvLYBQ+kau4eoFo4cmwlf3U37+HK1WENiLG6O3hHnu/n8b4AL2NaQPnsFWsWG1nrbfbPZ3j+Xvn6wJJWGkitUjahKFREcHSAFl5+jMqXULpTYP8X4ZkOYZ8M5V+1VhhSzqOH0lqsVYyDZbFIWf9UQJn51cNKBakULVWHvFMIlIMo4vULiXX7r4lWfY5FCYdABiOPADW2xuMg9++etlAcU4fpBl4Kf9GqWIs4XGmrVqJ9P5Jjto3J4bHyfF32v7HWC6vdwp81nvFHabMYj4AS9gmn6/90BQKEkN2OF43oRKsmq+IwFqt2HqMt7CakIYvdj5oQMu0j5lMY7JuYh1k2Ds=
#    bucket: ${ADMIN_BUCKET}
#    skip_cleanup: true
#    acl: public-read
#    local-dir: admin/build
#    on:
#      branch: ${DEPLOYMENT_BRANCH}
#      repo: ${REPOSITORY}
#      condition: "$MULTI_BRANCH == 0 && $TRAVIS_PULL_REQUEST == 'false' && $CURRENT_CI == 'travis'"
#  - provider: gcs
#    access_key_id:
#      secure: eSJfigRfZp7bwMBT61tes4NZZR5UnPSACWuD3seeLyMMflvfEiQBT30kMyQkcIA19cYUWuzCmdaUDGuphj8KrkPOfIqoPaG5ZM/zFbjgtJs3nNmpMt2GW/y5YFSqJR7ha0TYCUpPq9UonxEB/sdcifS7JRS0PmeEotZbcKMGmiCzDnFR8fNbDC1w1XZEfFoV+xtBYJCCDsZpPVjt+GXI+3OX31qnRCMv89aPU2lgmbUaF3oM+Bxc+9jQPEUmMKzOXt1AlIscJgkjyOIPTU9R1TsYtSNGzCxhEj2EtBdbtr2SKLdvJCaxABDtg6c0DOZSRSB5FP2kjLXm2TmtnFyn04R2RS7Cp3F5tueSpiK/51rI6oPc66OYMtWSINMhQzzWTiAdkBx2sekO9InbBgJMJgbcWt5nRvtzS/4mbCiDJxM+H4LuJHaqeCdDqZ51M1mf1HBh0diKIEn0o86fzUlPBtLZBLo/PCqGsJnLF+7VkG0AHExuJCSx8QHXfvP40+D3LtameHopx0lK+L8CMWwRzGJ5SDzzpfqoWZxwyzZjEvLzOdChWRb9jqPQDC1H48SFhsQt/eiwz0ZQq4v8I8DqQ3NkECYBoVgO7ozGN/pnqYK3i8xRnA47dGvSZrxQB32Eq0mkF6s8Rk7Xt6dI5ppNqdzjrCK2ZWijcGjBIQ769gQ=
#    secret_access_key:
#      secure: O4nNU4GlxBpnp1lJEEZKm0R3iUhK2V6qpu2JTxI4Vip6E5oAvXWJBc8keT75vbodRG2yYgmCf4HZhDnZRso6B7zY1SbE+oJjS6/jWM/Qkynf4qJ2/5NRvxjTuQsp99eqmclQ9J5CwhU690ZSZgC8eFaGN5Dwa2yJu5kBZHeUiDQgO3o3n1a2YCHBnOwQy7O7h6wj6d3iLThpfpdpLheqLF0DQ/c593Yy5mQgZRZkuqhLGWe94h8WyUtzJCmmYVP+XKNxbNKysCpD6zUulVTQ4XBYf5Z8kI2pAEP8UsTjqLZBjKdpyYqxoigyoL78hgs7KrYUBcCKW9qUsjRdXgNrsVvLYBQ+kau4eoFo4cmwlf3U37+HK1WENiLG6O3hHnu/n8b4AL2NaQPnsFWsWG1nrbfbPZ3j+Xvn6wJJWGkitUjahKFREcHSAFl5+jMqXULpTYP8X4ZkOYZ8M5V+1VhhSzqOH0lqsVYyDZbFIWf9UQJn51cNKBakULVWHvFMIlIMo4vULiXX7r4lWfY5FCYdABiOPADW2xuMg9++etlAcU4fpBl4Kf9GqWIs4XGmrVqJ9P5Jjto3J4bHyfF32v7HWC6vdwp81nvFHabMYj4AS9gmn6/90BQKEkN2OF43oRKsmq+IwFqt2HqMt7CakIYvdj5oQMu0j5lMY7JuYh1k2Ds=
#    bucket: ${DEV_ADMIN_BUCKET}
#    skip_cleanup: true
#    acl: public-read
#    local-dir: admin/build
#    on:
#      branch: ${TRAVIS_BRANCH}
#      repo: ${REPOSITORY}
#      condition: "$MULTI_BRANCH == 1 && $CURRENT_CI == 'travis'"
#  - provider: gcs
#    access_key_id:
#      secure: eSJfigRfZp7bwMBT61tes4NZZR5UnPSACWuD3seeLyMMflvfEiQBT30kMyQkcIA19cYUWuzCmdaUDGuphj8KrkPOfIqoPaG5ZM/zFbjgtJs3nNmpMt2GW/y5YFSqJR7ha0TYCUpPq9UonxEB/sdcifS7JRS0PmeEotZbcKMGmiCzDnFR8fNbDC1w1XZEfFoV+xtBYJCCDsZpPVjt+GXI+3OX31qnRCMv89aPU2lgmbUaF3oM+Bxc+9jQPEUmMKzOXt1AlIscJgkjyOIPTU9R1TsYtSNGzCxhEj2EtBdbtr2SKLdvJCaxABDtg6c0DOZSRSB5FP2kjLXm2TmtnFyn04R2RS7Cp3F5tueSpiK/51rI6oPc66OYMtWSINMhQzzWTiAdkBx2sekO9InbBgJMJgbcWt5nRvtzS/4mbCiDJxM+H4LuJHaqeCdDqZ51M1mf1HBh0diKIEn0o86fzUlPBtLZBLo/PCqGsJnLF+7VkG0AHExuJCSx8QHXfvP40+D3LtameHopx0lK+L8CMWwRzGJ5SDzzpfqoWZxwyzZjEvLzOdChWRb9jqPQDC1H48SFhsQt/eiwz0ZQq4v8I8DqQ3NkECYBoVgO7ozGN/pnqYK3i8xRnA47dGvSZrxQB32Eq0mkF6s8Rk7Xt6dI5ppNqdzjrCK2ZWijcGjBIQ769gQ=
#    secret_access_key:
#      secure: O4nNU4GlxBpnp1lJEEZKm0R3iUhK2V6qpu2JTxI4Vip6E5oAvXWJBc8keT75vbodRG2yYgmCf4HZhDnZRso6B7zY1SbE+oJjS6/jWM/Qkynf4qJ2/5NRvxjTuQsp99eqmclQ9J5CwhU690ZSZgC8eFaGN5Dwa2yJu5kBZHeUiDQgO3o3n1a2YCHBnOwQy7O7h6wj6d3iLThpfpdpLheqLF0DQ/c593Yy5mQgZRZkuqhLGWe94h8WyUtzJCmmYVP+XKNxbNKysCpD6zUulVTQ4XBYf5Z8kI2pAEP8UsTjqLZBjKdpyYqxoigyoL78hgs7KrYUBcCKW9qUsjRdXgNrsVvLYBQ+kau4eoFo4cmwlf3U37+HK1WENiLG6O3hHnu/n8b4AL2NaQPnsFWsWG1nrbfbPZ3j+Xvn6wJJWGkitUjahKFREcHSAFl5+jMqXULpTYP8X4ZkOYZ8M5V+1VhhSzqOH0lqsVYyDZbFIWf9UQJn51cNKBakULVWHvFMIlIMo4vULiXX7r4lWfY5FCYdABiOPADW2xuMg9++etlAcU4fpBl4Kf9GqWIs4XGmrVqJ9P5Jjto3J4bHyfF32v7HWC6vdwp81nvFHabMYj4AS9gmn6/90BQKEkN2OF43oRKsmq+IwFqt2HqMt7CakIYvdj5oQMu0j5lMY7JuYh1k2Ds=
#    bucket: ${CLIENT_BUCKET}
#    skip_cleanup: true
#    acl: public-read
#    local-dir: client/build
#    on:
#      branch: ${DEPLOYMENT_BRANCH}
#      repo: ${REPOSITORY}
#      condition: "$MULTI_BRANCH == 0 && $TRAVIS_PULL_REQUEST == 'false' && $CURRENT_CI == 'travis'"
#  - provider: gcs
#    access_key_id:
#      secure: eSJfigRfZp7bwMBT61tes4NZZR5UnPSACWuD3seeLyMMflvfEiQBT30kMyQkcIA19cYUWuzCmdaUDGuphj8KrkPOfIqoPaG5ZM/zFbjgtJs3nNmpMt2GW/y5YFSqJR7ha0TYCUpPq9UonxEB/sdcifS7JRS0PmeEotZbcKMGmiCzDnFR8fNbDC1w1XZEfFoV+xtBYJCCDsZpPVjt+GXI+3OX31qnRCMv89aPU2lgmbUaF3oM+Bxc+9jQPEUmMKzOXt1AlIscJgkjyOIPTU9R1TsYtSNGzCxhEj2EtBdbtr2SKLdvJCaxABDtg6c0DOZSRSB5FP2kjLXm2TmtnFyn04R2RS7Cp3F5tueSpiK/51rI6oPc66OYMtWSINMhQzzWTiAdkBx2sekO9InbBgJMJgbcWt5nRvtzS/4mbCiDJxM+H4LuJHaqeCdDqZ51M1mf1HBh0diKIEn0o86fzUlPBtLZBLo/PCqGsJnLF+7VkG0AHExuJCSx8QHXfvP40+D3LtameHopx0lK+L8CMWwRzGJ5SDzzpfqoWZxwyzZjEvLzOdChWRb9jqPQDC1H48SFhsQt/eiwz0ZQq4v8I8DqQ3NkECYBoVgO7ozGN/pnqYK3i8xRnA47dGvSZrxQB32Eq0mkF6s8Rk7Xt6dI5ppNqdzjrCK2ZWijcGjBIQ769gQ=
#    secret_access_key:
#      secure: O4nNU4GlxBpnp1lJEEZKm0R3iUhK2V6qpu2JTxI4Vip6E5oAvXWJBc8keT75vbodRG2yYgmCf4HZhDnZRso6B7zY1SbE+oJjS6/jWM/Qkynf4qJ2/5NRvxjTuQsp99eqmclQ9J5CwhU690ZSZgC8eFaGN5Dwa2yJu5kBZHeUiDQgO3o3n1a2YCHBnOwQy7O7h6wj6d3iLThpfpdpLheqLF0DQ/c593Yy5mQgZRZkuqhLGWe94h8WyUtzJCmmYVP+XKNxbNKysCpD6zUulVTQ4XBYf5Z8kI2pAEP8UsTjqLZBjKdpyYqxoigyoL78hgs7KrYUBcCKW9qUsjRdXgNrsVvLYBQ+kau4eoFo4cmwlf3U37+HK1WENiLG6O3hHnu/n8b4AL2NaQPnsFWsWG1nrbfbPZ3j+Xvn6wJJWGkitUjahKFREcHSAFl5+jMqXULpTYP8X4ZkOYZ8M5V+1VhhSzqOH0lqsVYyDZbFIWf9UQJn51cNKBakULVWHvFMIlIMo4vULiXX7r4lWfY5FCYdABiOPADW2xuMg9++etlAcU4fpBl4Kf9GqWIs4XGmrVqJ9P5Jjto3J4bHyfF32v7HWC6vdwp81nvFHabMYj4AS9gmn6/90BQKEkN2OF43oRKsmq+IwFqt2HqMt7CakIYvdj5oQMu0j5lMY7JuYh1k2Ds=
#    bucket: ${DEV_CLIENT_BUCKET}
#    skip_cleanup: true
#    acl: public-read
#    local-dir: client/build
#    on:
#      branch: ${TRAVIS_BRANCH}
#      repo: ${REPOSITORY}
#      condition: "$MULTI_BRANCH == 1 && $CURRENT_CI == 'travis'"
