apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "api-platform.fullname" . }}-cronjob
  labels:
    {{- include "api-platform.labels" . | nindent 4 }}
spec:
  schedule: '0 0 * * *'
  jobTemplate:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "api-platform.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "api-platform.serviceAccountName" . }}
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}-cronjob
              image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.php.image.pullPolicy }}
              args: ['bin/console', 'doctrine:fixtures:load', '--no-interaction']
              env:
                - name: OIDC_SERVER_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: oidc-server-url
                - name: OIDC_SERVER_URL_INTERNAL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: oidc-server-url-internal
                - name: TRUSTED_HOSTS
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-trusted-hosts
                - name: TRUSTED_PROXIES
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-trusted-proxies
                - name: APP_ENV
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-app-env
                - name: APP_DEBUG
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-app-debug
                - name: APP_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-app-secret
                - name: CORS_ALLOW_ORIGIN
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-cors-allow-origin
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: database-url
                - name: MERCURE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: mercure-url
                - name: MERCURE_PUBLIC_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: mercure-public-url
                - name: MERCURE_JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: mercure-jwt-secret
              lifecycle:
                preStop:
                  exec:
                    command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
              startupProbe:
                exec:
                  command: ['pgrep', '-f', '"composer|bin/console"']
                failureThreshold: 40
                periodSeconds: 3
              readinessProbe:
                exec:
                  command: ['pgrep', '-f', '"composer|bin/console"']
                periodSeconds: 3
              livenessProbe:
                exec:
                  command: ['pgrep', '-f', '"composer|bin/console"']
                periodSeconds: 3
