apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "api-platform.fullname" . }}-cronjob
  labels:
    {{- include "api-platform.labels" . | nindent 4 }}
spec:
  schedule: '0 0 * * *'
  jobTemplate:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "api-platform.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "api-platform.serviceAccountName" . }}
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}-cronjob
              image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.php.image.pullPolicy }}
              command: ['/bin/sh', '-c']
              args: ['composer install --prefer-dist --no-progress --no-interaction && bin/console doctrine:schema:drop --force --no-interaction && bin/console doctrine:migrations:version --delete --all --no-interaction && bin/console doctrine:migrations:migrate --no-interaction && bin/console doctrine:fixtures:load --no-interaction']
              env:
                - name: API_ENTRYPOINT_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-host
                - name: JWT_PASSPHRASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-jwt-passphrase
                - name: JWT_PUBLIC_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-jwt-public-key
                - name: JWT_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-jwt-secret-key
                - name: TRUSTED_HOSTS
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-trusted-hosts
                - name: TRUSTED_PROXIES
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-trusted-proxies
                - name: APP_ENV
                  value: "dev"
                - name: APP_DEBUG
                  value: "1"
                - name: APP_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-app-secret
                - name: CORS_ALLOW_ORIGIN
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: php-cors-allow-origin
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: database-url
                - name: MERCURE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: mercure-url
                - name: MERCURE_PUBLIC_URL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: mercure-public-url
                - name: MERCURE_JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "api-platform.fullname" . }}
                      key: mercure-jwt-secret
              lifecycle:
                preStop:
                  exec:
                    command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
              startupProbe:
                exec:
                  command:
                    - docker-healthcheck
                failureThreshold: 40
                periodSeconds: 3
              readinessProbe:
                exec:
                  command:
                    - docker-healthcheck
                periodSeconds: 3
              livenessProbe:
                exec:
                  command:
                    - docker-healthcheck
                periodSeconds: 3
