name: Cleanup

on:
  pull_request:
    types: [ closed ]

env:
  GKE_CLUSTER: api-platform-demo
  GCE_ZONE: europe-west1-c

jobs:
  cleanup:
    name: Uninstall K8s Release for Closed Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # gcloud does not work with Python 3.10 because collections.Mappings was removed in Python 3.10.
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.15
      - name: Auth gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
#          # https://github.com/google-github-actions/setup-gcloud/issues/128
#          version: '290.0.1'
          project_id: ${{ secrets.GKE_PROJECT }}
      - name: Configure gcloud
        run: |
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GCE_ZONE
      - name: Check for existing namespace
        id: k8s-namespace
        run: echo "::set-output name=namespace::$(kubectl get namespace pr-${{ github.event.number }} 2> /dev/null)"
      - name: Uninstall release
        if: steps.k8s-namespace.outputs.namespace != ''
        run: kubectl delete namespace pr-${{ github.event.number }}
