name: Cleanup

on:
  pull_request:
    types: [ closed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cleanup:
    name: Uninstall K8s Release for Closed Pull Request
    if: ${{ github.repository == 'api-platform/demo' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # gcloud does not work with Python 3.10 because "collections.Mappings" was removed in Python 3.10.
      -
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.15
      -
        name: Auth gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      -
        name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
      -
        name: Configure gcloud
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials api-platform-demo --zone europe-west1-c
      -
        name: Check for existing namespace
        id: k8s-namespace
        run: echo "namespace=$(kubectl get namespace pr-${{ github.event.number }} | tr -d '\n' 2> /dev/null)" >> $GITHUB_OUTPUT
      -
        name: Uninstall release
        if: steps.k8s-namespace.outputs.namespace != ''
        run: kubectl delete namespace pr-${{ github.event.number }}
