name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: GitHub Environment Name
        default: prod
        required: false
      url:
        type: string
        description: GitHub Environment Url (without scheme)
        required: true
      docker-images-version:
        type: string
        description: Docker Images Version
        default: latest
        required: false
      cors:
        type: string
        description: CORS
        required: true
      release:
        type: string
        description: Release Name
        required: true
      namespace:
        type: string
        description: Namespace Name
        required: true
      gke-cluster:
        type: string
        description: Google Kubernetes Engine Cluster
        required: true
      gke-zone:
        type: string
        description: Google Kubernetes Engine Zone
        required: true
    secrets:
      gke-credentials:
        description: Google Kubernetes Engine Credentials as JSON
        required: true
      gke-project:
        description: Google Kubernetes Engine Project
        required: true
      cloudflare-api-token:
        description: Cloudflare API Token
        required: true
      cloudflare-zone-id:
        description: Cloudflare Zone Id
        required: true
      keycloak-admin-password:
        description: Keycloak Admin Password
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.url }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      # gcloud does not work with Python 3.10 because "collections.Mappings" was removed in Python 3.10.
      -
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.15
      -
        name: Auth gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.gke-credentials }}
      -
        name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.gke-project }}
      -
        name: Configure gcloud
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials ${{ inputs.gke-cluster }} --zone ${{ inputs.gke-zone }}
      # https://github.com/helm/helm/issues/8036
      -
        name: Build helm dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami/
          helm repo add stable https://charts.helm.sh/stable/
          helm dependency build ./helm/api-platform
      -
        name: Lint Helm
        run: helm lint ./helm/api-platform/
      # Release name MUST start with a letter
      -
        name: Deploy
        run: |
          set -o pipefail
          helm upgrade ${{ inputs.release }} ./helm/api-platform \
            --install \
            --create-namespace \
            --debug \
            --wait \
            --namespace=${{ inputs.namespace }} \
            --set=app.version=${{ github.sha }} \
            --set=keycloak.image.registry=eu.gcr.io \
            --set=keycloak.image.repository=${{ secrets.gke-project }}/keycloak \
            --set=keycloak.image.tag=${{ inputs.docker-images-version }} \
            --set=keycloak.image.pullPolicy=Always \
            --set=keycloak.auth.adminPassword=${{ secrets.keycloak-admin-password }} \
            --set=keycloak.extraEnvVars[0].name=KC_HOSTNAME_URL \
            --set=keycloak.keycloakConfigCli.image.pullPolicy=Always \
            --set-string=keycloak.extraEnvVars[0].value=https://${{ inputs.url }}/oidc/ \
            --set=keycloak.extraEnvVars[1].name=KC_HOSTNAME_ADMIN_URL \
            --set-string=keycloak.extraEnvVars[1].value=https://${{ inputs.url }}/oidc/ \
            --set=keycloak.extraEnvVars[2].name=KEYCLOAK_PRODUCTION \
            --set-string=keycloak.extraEnvVars[2].value=true \
            --set=php.image.repository=eu.gcr.io/${{ secrets.gke-project }}/php \
            --set=php.image.tag=${{ inputs.docker-images-version }} \
            --set=php.image.pullPolicy=Always \
            --set=pwa.image.repository=eu.gcr.io/${{ secrets.gke-project }}/pwa \
            --set=pwa.image.tag=${{ inputs.docker-images-version }} \
            --set=pwa.image.pullPolicy=Always \
            --set=ingress.hosts[0].host=${{ inputs.url }} \
            --set=ingress.hosts[0].paths[0].path=/* \
            --set=ingress.hosts[0].paths[0].pathType=ImplementationSpecific \
            --set=external-dns.cloudflare.apiToken=${{ secrets.cloudflare-api-token }} \
            --set=external-dns.domainFilters={"${{ inputs.url }}"} \
            --set=external-dns.zoneIdFilters={${{ secrets.cloudflare-zone-id }}} \
            --set=php.corsAllowOrigin="^$(echo "${{ join(fromJSON(inputs.cors), '|') }}" | sed 's/\./\\./g')$" \
            --set=mercure.publicUrl=https://${{ inputs.url }}/.well-known/mercure \
            --set=mercure.jwtSecret="!ChangeThisMercureHubJWTSecretKey!" \
            --set=mercure.extraDirectives="demo \
            cors_origins ${{ join(fromJSON(inputs.cors), ' ') }}" \
            | sed --unbuffered '/USER-SUPPLIED VALUES/,$d'
      -
        name: Debug kube events
        if: failure()
        run: kubectl get events --namespace=${{ inputs.namespace }} --sort-by .metadata.creationTimestamp
