name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: GitHub Environment Name
        default: prod
        required: false
      url:
        type: string
        description: GitHub Environment Url (without scheme)
        required: true
      docker-images-version:
        type: string
        description: Docker Images Version
        default: latest
        required: false
      cors:
        type: string
        description: CORS
        required: true
      release:
        type: string
        description: Release Name
        required: true
      namespace:
        type: string
        description: Namespace Name
        required: true
      gke-cluster:
        type: string
        description: Google Kubernetes Engine Cluster
        required: true
      gke-zone:
        type: string
        description: Google Kubernetes Engine Zone
        required: true
    secrets:
      gke-credentials:
        description: Google Kubernetes Engine Credentials as JSON
        required: true
      gke-project:
        description: Google Kubernetes Engine Project
        required: true
      cloudflare-api-token:
        description: Cloudflare API Token
        required: true
      cloudflare-zone-id:
        description: Cloudflare Zone Id
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.url }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # gcloud does not work with Python 3.10 because collections.Mappings was removed in Python 3.10.
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.15
      - name: Auth gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.gke-credentials }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.gke-project }}
      - name: Configure gcloud
        run: |
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials ${{ inputs.gke-cluster }} --zone ${{ inputs.gke-zone }}
      # https://github.com/helm/helm/issues/8036
      - name: Build helm dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami/
          helm repo add stable https://charts.helm.sh/stable/
          helm dependency build ./helm/api-platform
      - name: Check for existing namespace
        id: k8s-namespace
        run: echo "::set-output name=namespace::$(kubectl get namespace ${{ inputs.namespace }} 2> /dev/null)"
      # Release name MUST start with a letter
      # GitHub doesn't support multilines environment variables (JWT_*_KEY)
      - name: Deploy in new namespace
        if: steps.k8s-namespace.outputs.namespace == ''
        run: |
          JWT_PASSPHRASE=$(openssl rand -base64 32)
          JWT_SECRET_KEY=$(openssl genpkey -pass file:<(echo "$JWT_PASSPHRASE") -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096)
          helm upgrade ${{ inputs.release }} ./helm/api-platform \
            --reuse-values \
            --install \
            --create-namespace \
            --namespace=${{ inputs.namespace }} \
            --set=app.version=${{ github.sha }} \
            --set=php.image.repository=eu.gcr.io/${{ secrets.gke-project }}/php \
            --set=php.image.tag=${{ inputs.docker-images-version }} \
            --set=php.image.pullPolicy=Always \
            --set=caddy.image.repository=eu.gcr.io/${{ secrets.gke-project }}/caddy \
            --set=caddy.image.tag=${{ inputs.docker-images-version }} \
            --set=caddy.image.pullPolicy=Always \
            --set=pwa.image.repository=eu.gcr.io/${{ secrets.gke-project }}/pwa \
            --set=pwa.image.tag=${{ inputs.docker-images-version }} \
            --set=pwa.image.pullPolicy=Always \
            --set=ingress.hosts[0].host=${{ inputs.url }} \
            --set=ingress.hosts[0].paths[0].path=/* \
            --set=ingress.hosts[0].paths[0].pathType=ImplementationSpecific \
            --set=external-dns.cloudflare.apiToken=${{ secrets.cloudflare-api-token }} \
            --set=external-dns.domainFilters={"${{ inputs.url }}"} \
            --set=external-dns.zoneIdFilters={${{ secrets.cloudflare-zone-id }}} \
            --set=php.jwt.secretKey="$JWT_SECRET_KEY" \
            --set=php.jwt.publicKey="$(openssl pkey -in <(echo "$JWT_SECRET_KEY") -passin file:<(echo "$JWT_PASSPHRASE") -pubout)" \
            --set=php.jwt.passphrase=$JWT_PASSPHRASE \
            --set=php.corsAllowOrigin="^$(echo "${{ join(fromJSON(inputs.cors), '|') }}" | sed 's/\./\\./g')$" \
            --set=php.host=${{ inputs.url }} \
            --set=mercure.publicUrl=https://${{ inputs.url }}/.well-known/mercure \
            --set=mercure.jwtSecret="!ChangeThisMercureHubJWTSecretKey!" \
            --set=postgresql.postgresqlPassword=$(openssl rand -base64 32 | tr -d "=+/") \
            --set=mercure.extraDirectives="demo \
            cors_origins ${{ join(fromJSON(inputs.cors), ' ') }}"
      - name: Upgrade namespace
        if: steps.k8s-namespace.outputs.namespace != ''
        run: |
          helm upgrade ${{ inputs.release }} ./helm/api-platform \
            --reuse-values \
            --install \
            --create-namespace \
            --namespace=${{ inputs.namespace }} \
            --set=app.version=${{ github.sha }} \
            --set=php.image.repository=eu.gcr.io/${{ secrets.gke-project }}/php \
            --set=php.image.tag=${{ inputs.docker-images-version }} \
            --set=php.image.pullPolicy=Always \
            --set=caddy.image.repository=eu.gcr.io/${{ secrets.gke-project }}/caddy \
            --set=caddy.image.tag=${{ inputs.docker-images-version }} \
            --set=caddy.image.pullPolicy=Always \
            --set=pwa.image.repository=eu.gcr.io/${{ secrets.gke-project }}/pwa \
            --set=pwa.image.tag=${{ inputs.docker-images-version }} \
            --set=pwa.image.pullPolicy=Always \
            --set=php.corsAllowOrigin="^$(echo "${{ join(fromJSON(inputs.cors), '|') }}" | sed 's/\./\\./g')$" \
            --set=mercure.jwtSecret="!ChangeThisMercureHubJWTSecretKey!" \
            --set=mercure.extraDirectives="demo \
            cors_origins ${{ join(fromJSON(inputs.cors), ' ') }}"
